### ISSUE TITLE
[Request] flutter_fbx3d_viewer

### ISSUE THREAD

**Issue by klaszlo8207** [flutterarsenal/FlutterArsenal#101]
github:     https://github.com/klaszlo8207/Flutter-FBX-3D-Viewer
tag:        flutter_fbx3d_viewer
excerpt:    This is a simple non textured Fbx animated 3d file viewer.
email-id:   lostinwar22@gmail.com
teaser:     https://raw.githubusercontent.com/klaszlo8207/Flutter-FBX-3D-Viewer/master/pix/gif.gif

**Comment by flutter-arsenal** [comment]
Thank you @klaszlo8207 for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_klaszlo8207/Flutter-FBX-3D-Viewer_](https://github.com/klaszlo8207/Flutter-FBX-3D-Viewer) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @klaszlo8207 for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @klaszlo8207 your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @klaszlo8207. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
