### ISSUE TITLE
[Request] steps_indicator

### ISSUE THREAD

**Issue by huextrat** [flutterarsenal/FlutterArsenal#103]
github:     https://github.com/huextrat/steps_indicator
tag:       steps line, status line, UI
excerpt:    Display a fully customizable steps line widget
email-id:   extrat.h@gmail.com
teaser:   https://raw.githubusercontent.com/huextrat/steps_indicator/master/example/screenshot.png

**Comment by flutter-arsenal** [comment]
Thank you @huextrat for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_huextrat/steps_indicator_](https://github.com/huextrat/steps_indicator) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @huextrat for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @huextrat your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @huextrat. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
