### ISSUE TITLE
[Request] Day Night Switcher

### ISSUE THREAD

**Issue by Skyost** [flutterarsenal/FlutterArsenal#105]
github: https://github.com/Skyost/DayNightSwitcher
tag: dark-mode
excerpt: A simple day / night switcher widget made in pure Dart. Allows to quickly show a beautiful dark mode switcher widget to your users.
email-id: me@skyost.eu
teaser: https://raw.githubusercontent.com/Skyost/DayNightSwitcher/master/screenshots/preview.gif

**Comment by flutter-arsenal** [comment]
Thank you @Skyost for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_Skyost/DayNightSwitcher_](https://github.com/Skyost/DayNightSwitcher) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @Skyost for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @Skyost for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_Skyost/DayNightSwitcher_](https://github.com/Skyost/DayNightSwitcher) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @karx for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @Skyost your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @Skyost. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by karx** [comment]
@Skyost this one is truly awesome !!

Really like it. Would be definitely using it in my future projects.
Might send an update to older ones too, this itself would become the highlight in the next release.

**Comment by Skyost** [comment]
@karx Thanks :wink:
