### ISSUE TITLE
[Request] Flutter Blue

### ISSUE THREAD

**Issue by IAmSarthakVerma** [flutterarsenal/FlutterArsenal#15]
github:  https://github.com/pauldemarco/flutter_blue  
tag:    Bluetooth    
excerpt:  FlutterBlue is a bluetooth plugin for Flutter, a new mobile SDK to help developers build modern apps for iOS and Android.  
email-id: hisarthakverma@gmail.com  
teaser:   https://raw.githubusercontent.com/pauldemarco/flutter_blue/master/site/flutterblue.png

**Comment by flutter-arsenal** [comment]
Thank you @IAmSarthakVerma for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_pauldemarco/flutter_blue_](https://github.com/pauldemarco/flutter_blue) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @IAmSarthakVerma your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @pauldemarco. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by flutter-arsenal** [comment]
Congratulations! @karx your request for adding a new event is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
