### ISSUE TITLE
[Request] Range Slider

### ISSUE THREAD

**Issue by IAmSarthakVerma** [flutterarsenal/FlutterArsenal#19]
github: https://github.com/boeledi/RangeSlider    
tag:    Slider    
excerpt:  An extension of the Flutter Material Slider to allow selection of a range of values via 2 thumbs.  
email-id:  hisarthakverma@gmail.com 
teaser:  https://camo.githubusercontent.com/b63e71909bfca406e5873d9d90ad0879e11f9255/68747470733a2f2f7777772e646964696572626f656c656e732e636f6d2f696d616765732f72616e67655f736c696465722e676966

**Comment by flutter-arsenal** [comment]
Thank you @IAmSarthakVerma for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_boeledi/RangeSlider_](https://github.com/boeledi/RangeSlider) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @IAmSarthakVerma your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @boeledi. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
