### ISSUE TITLE
[Request] Flutter Staggered Grid View

### ISSUE THREAD

**Issue by IAmSarthakVerma** [flutterarsenal/FlutterArsenal#20]
github:  https://github.com/letsar/flutter_staggered_grid_view  
tag:   Grid View     
excerpt: A Flutter staggered grid view which supports multiple columns with rows of varying sizes.   
email-id:   hisarthakverma@gmail.com
teaser:   https://raw.githubusercontent.com/letsar/flutter_staggered_grid_view/master/doc/images/example_01.PNG

**Comment by flutter-arsenal** [comment]
Thank you @IAmSarthakVerma for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_letsar/flutter_staggered_grid_view_](https://github.com/letsar/flutter_staggered_grid_view) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @IAmSarthakVerma your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @letsar. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
