### ISSUE TITLE
[Request] Flutter Sticky Header

### ISSUE THREAD

**Issue by IAmSarthakVerma** [flutterarsenal/FlutterArsenal#22]
github:  https://github.com/letsar/flutter_sticky_header   
tag:    UI Helper    
excerpt:   A Flutter implementation of sticky headers with a sliver as a child. 
email-id:  hisarthakverma@gmail.com 
teaser:  https://raw.githubusercontent.com/letsar/flutter_sticky_header/master/doc/images/sticky_header_all.gif

**Comment by flutter-arsenal** [comment]
Thank you @IAmSarthakVerma for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_letsar/flutter_sticky_header_](https://github.com/letsar/flutter_sticky_header) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @IAmSarthakVerma your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @letsar. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
