### ISSUE TITLE
[Request] Awesome Flutter Project

### ISSUE THREAD

**Issue by IAmSarthakVerma** [flutterarsenal/FlutterArsenal#23]
github:  https://github.com/xqwzts/flutter_radial_menu   
tag:  menu bar   
excerpt:  A radial menu widget for Flutter.  
email-id:  hisarthakverma@gmail.com 
teaser: https://raw.githubusercontent.com/xqwzts/flutter_radial_menu/master/screenshots/demo.gif

**Comment by flutter-arsenal** [comment]
Thank you @IAmSarthakVerma for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_xqwzts/flutter_radial_menu_](https://github.com/xqwzts/flutter_radial_menu) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @IAmSarthakVerma your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @xqwzts. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
