### ISSUE TITLE
[Request] Hidden Drawer Menu

### ISSUE THREAD

**Issue by IAmSarthakVerma** [flutterarsenal/FlutterArsenal#24]
github:   https://github.com/RafaelBarbosatec/hidden_drawer_menu  
tag:    Drawer    
excerpt:   Hidden Drawer Menu is a library for adding a beautiful drawer mode menu feature with perspective animation. 
email-id:  hisarthakverma@gmail.com 
teaser:  https://github.com/RafaelBarbosatec/hidden_drawer_menu/raw/master/imgs/example.gif

**Comment by flutter-arsenal** [comment]
Thank you @IAmSarthakVerma for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_RafaelBarbosatec/hidden_drawer_menu_](https://github.com/RafaelBarbosatec/hidden_drawer_menu) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @IAmSarthakVerma your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @RafaelBarbosatec. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
