### ISSUE TITLE
[Request] Flutter Fluid Slider

### ISSUE THREAD

**Issue by IAmSarthakVerma** [flutterarsenal/FlutterArsenal#25]
github:   https://github.com/rvamsikrishna/flutter_fluid_slider  
tag:   Slider     
excerpt:  A fluid design slider that works just like the Slider material widget.  
email-id:  hisarthakverma@gmail.com 
teaser:   https://camo.githubusercontent.com/d811ab18d6a87537dec815bf1937c48ce9a31dfc/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f56714d427277485443495f65396e633443304962794432572d4279746a343656564b5764723139384d71564a32556e7a513852335735764b394a726961794c4e47467839526b504b4141436c

**Comment by flutter-arsenal** [comment]
Thank you @IAmSarthakVerma for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_rvamsikrishna/flutter_fluid_slider_](https://github.com/rvamsikrishna/flutter_fluid_slider) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @IAmSarthakVerma your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @rvamsikrishna. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
