### ISSUE TITLE
[Request] Flutter Offline

### ISSUE THREAD

**Issue by IAmSarthakVerma** [flutterarsenal/FlutterArsenal#26]
github:  https://github.com/jogboms/flutter_offline   
tag:  UI Helper      
excerpt:  A tidy utility to handle offline/online connectivity like a Boss. It provides support for both iOS and Android platforms (offcourse).  
email-id: hisarthakverma@gmail.com  
teaser:  https://raw.githubusercontent.com/jogboms/flutter_offline/master/screenshots/demo_1.gif

**Comment by flutter-arsenal** [comment]
Thank you @IAmSarthakVerma for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_jogboms/flutter_offline_](https://github.com/jogboms/flutter_offline) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @IAmSarthakVerma your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @jogboms. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
