### ISSUE TITLE
[Request] Scroll To Index

### ISSUE THREAD

**Issue by IAmSarthakVerma** [flutterarsenal/FlutterArsenal#27]
github:  https://github.com/quire-io/scroll-to-index   
tag:    UI Helper    
excerpt:  This package provides the scroll to index mechanism for fixed/variable row height for Flutter scrollable widget.  
email-id: hisarthakverma@gmail.com  
teaser:

**Comment by flutter-arsenal** [comment]
Thank you @IAmSarthakVerma for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_quire-io/scroll-to-index_](https://github.com/quire-io/scroll-to-index) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @IAmSarthakVerma your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @quire-io. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
