### ISSUE TITLE
[Request] Flutter Infinite Listview

### ISSUE THREAD

**Issue by IAmSarthakVerma** [flutterarsenal/FlutterArsenal#28]
github: https://github.com/fluttercommunity/flutter_infinite_listview    
tag:    List View    
excerpt:  ListView with items that can be scrolled infinitely in both directions.  
email-id: hisarthakverma@gmail.com  
teaser:   https://github.com/fluttercommunity/flutter_infinite_listview/raw/readme/example.gif

**Comment by flutter-arsenal** [comment]
Thank you @IAmSarthakVerma for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_fluttercommunity/flutter_infinite_listview_](https://github.com/fluttercommunity/flutter_infinite_listview) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @IAmSarthakVerma your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @fluttercommunity. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
