### ISSUE TITLE
[Request] Awesome Flutter Project

### ISSUE THREAD

**Issue by xsahil03x** [flutterarsenal/FlutterArsenal#29]
github:     https://github.com/xsahil03x/giffy_dialog 
tag:        dialogs 
excerpt:    A flutter package for creating Giffy and animated dialogs. (Supports flare animations too) 
email-id:   xdsahil@gmail.com 
teaser: https://user-images.githubusercontent.com/25670178/51350846-4504b680-1acf-11e9-8f9d-d6704742ff21.gi

**Comment by flutter-arsenal** [comment]
Congratulations! @karx your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @xsahil03x. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by karx** [comment]
Thanks, @xsahil03x for adding your awesome weapon to the Arsenal. 
It is now live on [Flutter Arsenal](https://flutterarsenal.com/projects/fa-git-giffy-dialog)

Also, welcome to the list of [Top Contributors](https://flutterarsenal.com/top-contributors/) of Flutter Arsenal.
The team has a special surprise for Top 3 each month.

**Comment by karx** [comment]
Also, c @all-contributors please add @xsahil03x for content and ideas.
