### ISSUE TITLE
[Request] flutter challenges

### ISSUE THREAD

**Issue by javico2609** [flutterarsenal/FlutterArsenal#33]
github: https://github.com/javico2609/flutter-challenges    
tag:   UI Kit     
excerpt:  18 templates, Redux, CRUD Sqlite and Firebase, http request, webview, google and firebase auth, global notification strategy, create and preview PDF, create and load csv, pagination, infinite scroll, touch id, map, change theme, custom fonts, download & share files and more.  
email-id: javico2609@gmail.com  
teaser:  https://github.com/javico2609/flutter-challenges/raw/master/ss8.png

**Comment by flutter-arsenal** [comment]
Thank you @IAmSarthakVerma for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_javico2609/flutter-challenges_](https://github.com/javico2609/flutter-challenges) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @IAmSarthakVerma for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_javico2609/flutter-challenges_](https://github.com/javico2609/flutter-challenges) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by IAmSarthakVerma** [comment]
Hey @javico2609 thanks for adding your tool to Flutter Arsenal.

I updated the issue you raised to match something our bot could understand, and it ended up attribute.
@all-contributors add @javico2609 for ideas and content.

**Comment by flutter-arsenal** [comment]
Congratulations! @undefined your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @javico2609. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by IAmSarthakVerma** [comment]
@javico2609 Please add a license file in your repo.

**Comment by karx** [comment]
@javico2609 Gentle reminder for adding license information for your plugin.

**Comment by javico2609** [comment]
Ok, np

**Comment by karx** [comment]
I see you have added the license file @javico2609 
Closing this issue.
