### ISSUE TITLE
Pick the "Project Names" from the "Issue Names".

### ISSUE THREAD

**Issue by IAmSarthakVerma** [flutterarsenal/FlutterArsenal#36]
## Expected behaviour

The project names should be picked from the Issue name instead of the repo name.

**Comment by karx** [comment]
Updated the webhook endpoint to use issue title instead.
Also updated the Regex we used to parse different fields from the issue. Let's keep this in observation as we see more contributions come in.

**Comment by karx** [comment]
Closing this, after observing it working for #38 .
