### ISSUE TITLE
Make the Flutter Arsenal website responsive

### ISSUE THREAD

**Issue by IAmSarthakVerma** [flutterarsenal/FlutterArsenal#37]
### The Problem
The website needs to be responsive and support multiple screen sizes. The current UI is broken for smaller screens.

![Screenshot 2019-07-16 at 2 34 18 PM](https://user-images.githubusercontent.com/20480867/61281252-f793a880-a7d6-11e9-8a93-5d179a9cafb4.png) ![Screenshot 2019-07-16 at 2 34 48 PM](https://user-images.githubusercontent.com/20480867/61281256-f95d6c00-a7d6-11e9-933e-4e09a5f590b2.png)

### How to get started to contribute to this issue.

The layouts of the website are made with [BOOTSTRAP 4](https://getbootstrap.com/docs/4.0/getting-started/introduction/)

The root folder for the website is [docs](https://github.com/flutterarsenal/FlutterArsenal/tree/master/docs) and all the HTML templates can be found in the [_layouts](https://github.com/flutterarsenal/FlutterArsenal/tree/master/docs/_layouts) folder.

**Comment by butterflydesign** [comment]
I'm not getting this issue in Chrome web browser. Has this been fixed already?

**Comment by IAmSarthakVerma** [comment]
@butterflydesign The issue has not been fixed yet. The main problem is with smaller screen devices(some tablets and mobile phones). 
To reproduce is just open any project cards present on the home page by clicking on the title of the card in any mobile device or you can also check this via a responsive design checker online.

**Comment by IAmSarthakVerma** [comment]
Made some changes in the fa_project layout and it looks better now. Pictures and tables are still something that requires to be worked on.

**Comment by karx** [comment]
closing this with reference to https://github.com/flutterarsenal/FlutterArsenal/pull/49
