### ISSUE TITLE
[Request] Photo View

### ISSUE THREAD

**Issue by renancaraujo** [flutterarsenal/FlutterArsenal#38]
github:   https://github.com/renancaraujo/photo_view  
tag:    images    
excerpt:  📸 Easy to use yet very customizable zoomable image widget for Flutter  
email-id:  renancaraujo@outlook.com  
teaser:   https://user-images.githubusercontent.com/6718144/56463745-45ec0380-63b0-11e9-8e56-0dba5deabb1a.gif

**Comment by flutter-arsenal** [comment]
Thank you @renancaraujo for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_renancaraujo/photo_view_](https://github.com/renancaraujo/photo_view) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @renancaraujo for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @renancaraujo your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @renancaraujo. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by karx** [comment]
@renancaraujo your awesome widget is now live.
I am _working on_ adding the permalink too to the flutter-arsenal bot response, in the meanwhile,
here: [Photo View page](https://flutterarsenal.com/projects/fa-git-photo-view).

Also, welcome to the list of [Top Contributors](https://flutterarsenal.com/top-contributors/).


Cheers.
