### ISSUE TITLE
Markdown table display error

### ISSUE THREAD

**Issue by VincentTam** [flutterarsenal/FlutterArsenal#47]
## Expected behaviour
A table
## Steps to reproduce the behaviour
Browser https://flutterarsenal.com/projects/fa-git-flutter-blue
## Other
![Screenshot_2019-07-24 flutter_blue](https://user-images.githubusercontent.com/5748535/61755325-5d73c780-adb7-11e9-9525-ef53611769d9.png)

**Comment by karx** [comment]
Thanks for pointing this out.

Surprised that tables are not showing up. I'll take this up

**Comment by karx** [comment]
Fixed. Please check and confirm.

Also, @all-contributors please add @VincentTam for reporting a bug.
