### ISSUE TITLE
[Request] Awesome Flutter Project

### ISSUE THREAD

**Issue by manojkumawat003** [flutterarsenal/FlutterArsenal#53]
github:   https://github.com/manojkumawat003/awesome_login  
tag:   awesome login     
excerpt:  An awesome login screen with some animation stuff.  
email-id:  manojkumawat003@gmail.com 
teaser:  https://github.com/manojkumawat003/awesome_login/blob/master/awesome_login.gif

**Comment by flutter-arsenal** [comment]
Thank you @manojkumawat003 for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_manojkumawat003/awesome_login_](https://github.com/manojkumawat003/awesome_login) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @manojkumawat003 for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @manojkumawat003 your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @manojkumawat003. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by karx** [comment]
@manojkumawat003 I would urge you to add a license file to your repository.

Your page is now live at: https://flutterarsenal.com/projects/fa-git-awesome-login

**Comment by IAmSarthakVerma** [comment]
@manojkumawat003 Add the licence file in your repository.

**Comment by karx** [comment]
@manojkumawat003 gentle reminder to add License file to your Awesome login repository.

**Comment by karx** [comment]
@manojkumawat003 created a PR on your repository with MIT license. Please approve and maintain. 
Thanks

**Comment by IAmSarthakVerma** [comment]
@manojkumawat003 You repo is listed on FlutterArsenal without any license under Free category. If you want to change this please update the license. Closing this for now.
