### ISSUE TITLE
[Request] Animated-Text-Kit

### ISSUE THREAD

**Issue by karx** [flutterarsenal/FlutterArsenal#58]
github:     https://github.com/aagarwal1012/Animated-Text-Kit
tag:        animate
excerpt:    🔔 A flutter package to create cool and beautiful text animations. 
email-id:  kartik.arora1214@gmail.com 
teaser:     https://raw.githubusercontent.com/aagarwal1012/Animated-Text-Kit/master/display/scale.gif

**Comment by flutter-arsenal** [comment]
Thank you @karx for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_aagarwal1012/Animated-Text-Kit_](https://github.com/aagarwal1012/Animated-Text-Kit) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @karx for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @karx your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @aagarwal1012. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
