### ISSUE TITLE
[Request] Liquid Pull To Refresh

### ISSUE THREAD

**Issue by aagarwal1012** [flutterarsenal/FlutterArsenal#60]
github:  [https://github.com/aagarwal1012/Liquid-Pull-To-Refresh](https://github.com/aagarwal1012/Liquid-Pull-To-Refresh)   
tag:    refresh-indicator    
excerpt: 🔁 A custom refresh indicator for flutter.   
email-id:  aagarwal9782@gmail.com 
teaser: https://github.com/aagarwal1012/Liquid-Pull-To-Refresh/blob/master/display/liquid_false.gif?raw=true

**Comment by flutter-arsenal** [comment]
Thank you @aagarwal1012 for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_aagarwal1012/Liquid-Pull-To-Refresh_](https://github.com/aagarwal1012/Liquid-Pull-To-Refresh) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @aagarwal1012 for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @aagarwal1012 for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_aagarwal1012/Liquid-Pull-To-Refresh_](https://github.com/aagarwal1012/Liquid-Pull-To-Refresh) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @aagarwal1012 for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @aagarwal1012 for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_aagarwal1012/Liquid-Pull-To-Refresh_](https://github.com/aagarwal1012/Liquid-Pull-To-Refresh) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @aagarwal1012 for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @aagarwal1012 your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @aagarwal1012. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
