### ISSUE TITLE
[Request] Flutter SpinKit

### ISSUE THREAD

**Issue by aagarwal1012** [flutterarsenal/FlutterArsenal#62]
github:     https://github.com/jogboms/flutter_spinkit
tag:        loading-indicators
excerpt:    ✨ A collection of loading indicators animated with flutter.
email-id:   aagarwal9782@gmail.com
teaser:     https://raw.githubusercontent.com/ybq/AndroidSpinKit/master/art/RotatingPlane.gif

**Comment by flutter-arsenal** [comment]
Thank you @aagarwal1012 for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_jogboms/flutter_spinkit_](https://github.com/jogboms/flutter_spinkit) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @aagarwal1012 for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @aagarwal1012 for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_jogboms/flutter_spinkit_](https://github.com/jogboms/flutter_spinkit) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @aagarwal1012 your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @jogboms. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
