### ISSUE TITLE
[Request] IntroViews Flutter

### ISSUE THREAD

**Issue by aagarwal1012** [flutterarsenal/FlutterArsenal#63]
github: https://github.com/aagarwal1012/IntroViews-Flutter    
tag: walkthrough       
excerpt: ☀️ A Flutter package for some material design app intro screens with some cool animations.   
email-id: aagarwal9782@gmail.com  
teaser:  https://raw.githubusercontent.com/aagarwal1012/IntroViews-Flutter/master/display/output.gif

**Comment by flutter-arsenal** [comment]
Thank you @aagarwal1012 for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_aagarwal1012/IntroViews-Flutter_](https://github.com/aagarwal1012/IntroViews-Flutter) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @aagarwal1012 for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @aagarwal1012 for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_aagarwal1012/IntroViews-Flutter_](https://github.com/aagarwal1012/IntroViews-Flutter) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by IAmSarthakVerma** [comment]
Hello @aagarwal1012, I have edited the tags as currently, only one tag is allowed.

**Comment by flutter-arsenal** [comment]
Congratulations! @aagarwal1012 your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @aagarwal1012. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
