### ISSUE TITLE
[Request] flutter_html (`Html` widget)

### ISSUE THREAD

**Issue by Sub6Resources** [flutterarsenal/FlutterArsenal#68]
github: https://github.com/Sub6Resources/flutter_html    
tag: html       
excerpt: Render static html and css into the Flutter widget tree. Renders over 70 different html elements!   
email-id: sub6resources@gmail.com  
teaser:  https://raw.githubusercontent.com/Sub6Resources/flutter_html/master/.github/flutter_html_screenshot.png

**Comment by flutter-arsenal** [comment]
Thank you @Sub6Resources for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_Sub6Resources/flutter_html_](https://github.com/Sub6Resources/flutter_html) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @Sub6Resources for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @Sub6Resources your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @Sub6Resources. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
