### ISSUE TITLE
[Request] Flutter Bitmap: Image editing with a help from the FFI

### ISSUE THREAD

**Issue by renancaraujo** [flutterarsenal/FlutterArsenal#71]
github:  https://github.com/renancaraujo/bitmap   
tag:    Image   
excerpt:  A minimalist Flutter package to perform fast bitmaps operations. The focus here is to provide a cool bitmap manipulation interface.  
email-id:   renancaraujo@outlook.com  
teaser:  https://github.com/renancaraujo/bitmap/blob/master/transform.jpg

**Comment by flutter-arsenal** [comment]
Thank you @renancaraujo for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_renancaraujo/bitmap_](https://github.com/renancaraujo/bitmap) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @renancaraujo for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @renancaraujo for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_renancaraujo/bitmap_](https://github.com/renancaraujo/bitmap) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @renancaraujo your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @renancaraujo. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
