### ISSUE TITLE
[Request] Rate My App

### ISSUE THREAD

**Issue by Skyost** [flutterarsenal/FlutterArsenal#79]
github:     https://github.com/Skyost/rate_my_app
tag:        app-rating
excerpt:    This plugin allows to kindly ask users to rate your app if custom conditions are met (eg. install time, number of launches, etc...).
email-id:   me@skyost.eu
teaser:  https://raw.githubusercontent.com/Skyost/rate_my_app/master/screenshots/android.png

**Comment by flutter-arsenal** [comment]
Thank you @Skyost for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_Skyost/rate_my_app_](https://github.com/Skyost/rate_my_app) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @Skyost for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @Skyost for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_Skyost/rate_my_app_](https://github.com/Skyost/rate_my_app) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @karx for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @Skyost your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @Skyost. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by karx** [comment]
Thanks for this amazing addition to Flutter Arsenal @Skyost, this rating widget, really practical for the ecosystem. Kudos!

**Comment by Skyost** [comment]
No problem @karx, the pleasure is all mine !
