### ISSUE TITLE
[Request] BubbleShowcase

### ISSUE THREAD

**Issue by Skyost** [flutterarsenal/FlutterArsenal#81]
github:     https://github.com/Skyost/BubbleShowcase
tag:        showcase
excerpt:    BubbleShowcase is a small but powerful flutter package that allows you to highlight specific parts of your app to explain them to the user or to show your app new features.
email-id:   me@skyost.eu
teaser:     https://raw.githubusercontent.com/Skyost/BubbleShowcase/master/screenshots/preview.gif

**Comment by flutter-arsenal** [comment]
Thank you @Skyost for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_Skyost/BubbleShowcase_](https://github.com/Skyost/BubbleShowcase) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @Skyost for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @Skyost for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_Skyost/BubbleShowcase_](https://github.com/Skyost/BubbleShowcase) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @karx for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @Skyost your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @Skyost. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
