### ISSUE TITLE
[Request] Dalocale

### ISSUE THREAD

**Issue by mauriciotogneri** [flutterarsenal/FlutterArsenal#82]
github: https://github.com/mauriciotogneri/dalocale    
tag: localization        
excerpt: A Flutter package to easily support internationalization and localization in your project.   
email-id: mauricio.togneri@gmail.com   
teaser: none at the moment

**Comment by karx** [comment]
Hi @mauriciotogneri 
Love the work you are doing. Would it be okay if we used GitHub links to your package instead of dev.to

Flutter Arsenal as of now only supports packages listed on Github as of now. 
We can start by adding more options for sources steadily.

**Comment by karx** [comment]
Same would be valid for #83 #84 and #86

**Comment by flutter-arsenal** [comment]
Thank you @mauriciotogneri for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_mauriciotogneri/dalocale_](https://github.com/mauriciotogneri/dalocale) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @mauriciotogneri for content and ideas.

**Comment by mauriciotogneri** [comment]
Hi @karx 
Thank you for the amazing work you are doing with this web site!
PRs fixed

**Comment by flutter-arsenal** [comment]
Congratulations! @mauriciotogneri your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @mauriciotogneri. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by karx** [comment]
All live now:
https://flutterarsenal.com/projects/fa-git-dalocale
https://flutterarsenal.com/projects/fa-git-daassets
https://flutterarsenal.com/projects/fa-git-dapackages
https://flutterarsenal.com/projects/fa-git-dahttp
