### ISSUE TITLE
[Request] Daassets 

### ISSUE THREAD

**Issue by mauriciotogneri** [flutterarsenal/FlutterArsenal#84]
github: https://github.com/mauriciotogneri/daassets     
tag: assets generator        
excerpt: A Flutter package to automatically generate a class containing references to all assets in your project.    
email-id: mauricio.togneri@gmail.com  
teaser: none at the moment

**Comment by flutter-arsenal** [comment]
Thank you @mauriciotogneri for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_mauriciotogneri/daassets_](https://github.com/mauriciotogneri/daassets) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @mauriciotogneri for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @mauriciotogneri your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @mauriciotogneri. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
