### ISSUE TITLE
[Request] Dahttp

### ISSUE THREAD

**Issue by mauriciotogneri** [flutterarsenal/FlutterArsenal#86]
github: https://github.com/mauriciotogneri/dahttp    
tag: http       
excerpt: HTTP wrapper for Dart with integrated logger design to be used for REST APIs.   
email-id: mauricio.togneri@gmail.com  
teaser: none at the moment

**Comment by flutter-arsenal** [comment]
Thank you @mauriciotogneri for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_mauriciotogneri/dahttp_](https://github.com/mauriciotogneri/dahttp) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @mauriciotogneri for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @mauriciotogneri your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @mauriciotogneri. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by flutter-arsenal** [comment]
Congratulations! @mauriciotogneri your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @mauriciotogneri. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
