### ISSUE TITLE
[Request] Awesome Flutter Project

### ISSUE THREAD

**Issue by rodrigordgfs** [flutterarsenal/FlutterArsenal#89]
github:    https://github.com/fluttership/Twitch-Clone-Flutter  
tag:   clone-app    
excerpt:  Twitch Stream Platform App Clone  
email-id:  rodrigo.viegas@ulbra.inf.br  
teaser:  https://i.imgur.com/O9TYsCe.gif

**Comment by flutter-arsenal** [comment]
Thank you @rodrigordgfs for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_fluttership/Twitch-Clone-Flutter_](https://github.com/fluttership/Twitch-Clone-Flutter) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @rodrigordgfs for content and ideas.

**Comment by IAmSarthakVerma** [comment]
@rodrigordgfs Please update the teaser link. It should be a link to a gif/png/jpg or any other similar format file which displays a demo/screenshot.

**Comment by rodrigordgfs** [comment]
https://i.imgur.com/O9TYsCe.mp4

**Comment by karx** [comment]
We do not support mp4 format on the FE as of now.
Give me today - to see how much effort would it be to add this feature. It would be a nice addition.

In the meantime, @rodrigordgfs is there a gif version we can use?

**Comment by rodrigordgfs** [comment]
https://i.imgur.com/O9TYsCe.gif

**Comment by flutter-arsenal** [comment]
Thank you @rodrigordgfs for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_fluttership/Twitch-Clone-Flutter_](https://github.com/fluttership/Twitch-Clone-Flutter) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @IAmSarthakVerma for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @rodrigordgfs your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @fluttership. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
