### ISSUE TITLE
[Request] EzLocalization

### ISSUE THREAD

**Issue by Skyost** [flutterarsenal/FlutterArsenal#93]
github:     https://github.com/Skyost/EzLocalization
tag:        localization
excerpt:    Add an asset-based localization system to your app in just a few lines of code !
email-id:   me@skyost.eu
teaser:     https://user-images.githubusercontent.com/3882599/69460222-de49cc80-0d73-11ea-9875-4c2cda62a307.png

**Comment by flutter-arsenal** [comment]
Thank you @Skyost for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_Skyost/EzLocalization_](https://github.com/Skyost/EzLocalization) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @Skyost for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @Skyost for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_Skyost/EzLocalization_](https://github.com/Skyost/EzLocalization) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @Skyost for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @Skyost your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @Skyost. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
