### ISSUE TITLE
[Request] Explode View

### ISSUE THREAD

**Issue by hemilpanchiwala** [flutterarsenal/FlutterArsenal#95]
github: https://github.com/mdg-soc-19/explode-view 
tag: explode 
excerpt: :boom:A beautiful explosion animation for Flutter. 
email-id: hemilmodi54321@gmail.com 
teaser: https://raw.githubusercontent.com/mdg-soc-19/explode-view/master/gif/explode-view.gif

**Comment by flutter-arsenal** [comment]
Thank you @hemilpanchiwala for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_mdg-soc-19/explode-view_](https://github.com/mdg-soc-19/explode-view) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @hemilpanchiwala for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @hemilpanchiwala for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_mdg-soc-19/explode-view_](https://github.com/mdg-soc-19/explode-view) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @hemilpanchiwala for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @hemilpanchiwala for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_mdg-soc-19/explode-view_](https://github.com/mdg-soc-19/explode-view) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @hemilpanchiwala for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @hemilpanchiwala for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_mdg-soc-19/explode-view_](https://github.com/mdg-soc-19/explode-view) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @hemilpanchiwala for content and ideas.

**Comment by flutter-arsenal** [comment]
Thank you @hemilpanchiwala for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_mdg-soc-19/explode-view_](https://github.com/mdg-soc-19/explode-view) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @hemilpanchiwala for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @hemilpanchiwala your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @mdg-soc-19. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)

**Comment by karx** [comment]
@hemilpanchiwala 
[Explode View](https://flutterarsenal.com/projects/fa-git-explode-view) is now live on https://flutterarsenal.com
![image](https://user-images.githubusercontent.com/7826138/71547873-969a0e80-29cb-11ea-8e3c-c9de0d328af4.png)
