### ISSUE TITLE
[Request] Flutter UIs and animations

### ISSUE THREAD

**Issue by arleyhr** [flutterarsenal/FlutterArsenal#97]
github:  https://github.com/arleyhr/flutter_challenges    
tag: ui       
excerpt: A collection of UI challenges, clones and animations    
email-id:  arleyhr@gmail.com 
teaser:  https://res.cloudinary.com/arleyhr/image/upload/v1577809900/flutter/travel-app/demo_bpzzdm.gif

**Comment by flutter-arsenal** [comment]
Thank you @arleyhr for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_arleyhr/flutter_challenges_](https://github.com/arleyhr/flutter_challenges) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @arleyhr for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @arleyhr your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @arleyhr. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
