### ISSUE TITLE
[Request] FlutterWeekView

### ISSUE THREAD

**Issue by Skyost** [flutterarsenal/FlutterArsenal#99]
github: https://github.com/Skyost/FlutterWeekView
tag: calendar
excerpt: A customizable week view which is able to display events, be scrolled, be zoomed-in, out and more !
email-id: me@skyost.eu
teaser: https://raw.githubusercontent.com/Skyost/FlutterWeekView/master/screenshots/week_view.gif

**Comment by flutter-arsenal** [comment]
Thank you @Skyost for submitting a new weapon for the __FlutterArsenal__.
The github repository: [_Skyost/FlutterWeekView_](https://github.com/Skyost/FlutterWeekView) is now awaiting approval from __admins__.

Kudos to you for contributing! cc @all-contributors please add @Skyost for content and ideas.

**Comment by flutter-arsenal** [comment]
Congratulations! @Skyost your request is now approved and live on [__FlutterArsenal__](https://flutterarsenal.com).

Ping! @Skyost. Your project is now listed.
Please help and support us in maintaining the biggest arsenal of Flutter weapons.
[![Tip Me via PayPal](https://img.shields.io/badge/PayPal-tip%20me-green.svg?logo=paypal)](https://www.paypal.me/karx01)
